version: "3.9"
services:
  aas-repository:
    image: "eclipsebasyx/aas-repository:2.0.0-SNAPSHOT"
    ports:
      - "8081:8081"
    networks:
      - backend
  sm-repository:
    image: "eclipsebasyx/submodel-repository:2.0.0-SNAPSHOT"
    ports:
      - "8082:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge